/**
 * BibTeX generation tool
 */

import { Paper, BibTeXEntry } from '../types.js';
import { getByDoi, getByArxivId } from './lookup.js';
import { searchPapers } from './search.js';
import { generateBibTeX } from '../utils/bibtex.js';
import { findBestMatch } from '../utils/similarity.js';

interface GetBibTeXOptions {
  doi?: string;
  arxivId?: string;
  title?: string;
  customKey?: string;
}

interface BibTeXResult {
  bibtex: string;
  entryKey: string;
  paper: Paper | null;
  source: string;
  warnings: string[];
}

/**
 * Get BibTeX entry for a paper
 */
export async function getBibTeX(options: GetBibTeXOptions): Promise<BibTeXResult> {
  const result: BibTeXResult = {
    bibtex: '',
    entryKey: '',
    paper: null,
    source: 'unknown',
    warnings: []
  };

  let paper: Paper | null = null;

  // Try DOI lookup first (most reliable)
  if (options.doi) {
    const doiResult = await getByDoi(options.doi);
    if (doiResult.paper) {
      paper = doiResult.paper;
      result.source = doiResult.sources.join(', ');
    } else {
      result.warnings.push(`DOI "${options.doi}" not found`);
    }
  }

  // Try arXiv ID lookup
  if (!paper && options.arxivId) {
    const arxivResult = await getByArxivId(options.arxivId);
    if (arxivResult.paper) {
      paper = arxivResult.paper;
      result.source = arxivResult.sources.join(', ');
    } else {
      result.warnings.push(`arXiv ID "${options.arxivId}" not found`);
    }
  }

  // Try title search
  if (!paper && options.title) {
    const searchResult = await searchPapers(options.title, { limit: 5 });
    if (searchResult.papers.length > 0) {
      // Find best match
      const match = findBestMatch({ title: options.title }, searchResult.papers, 0.7);
      if (match) {
        paper = match.paper;
        result.source = searchResult.sourcesQueried.join(', ');
        if (match.similarity < 0.9) {
          result.warnings.push(`Title match confidence: ${(match.similarity * 100).toFixed(1)}%`);
        }
      } else {
        result.warnings.push('No close title match found, using best result');
        paper = searchResult.papers[0];
        result.source = searchResult.sourcesQueried.join(', ');
      }
    } else {
      result.warnings.push('No papers found matching the title');
    }
  }

  if (!paper) {
    result.warnings.push('Could not find paper in any database');
    return result;
  }

  // Generate BibTeX
  const entry = generateBibTeX(paper, options.customKey);

  result.bibtex = entry.raw;
  result.entryKey = entry.citationKey;
  result.paper = paper;

  // Add warnings for incomplete data
  if (!paper.doi) {
    result.warnings.push('No DOI available for this paper');
  }
  if (paper.authors.length === 0) {
    result.warnings.push('No author information available');
  }
  if (!paper.venue && paper.venueType !== 'arxiv') {
    result.warnings.push('No venue information available');
  }

  return result;
}

/**
 * Get multiple BibTeX entries
 */
export async function getBibTeXBatch(
  queries: GetBibTeXOptions[]
): Promise<BibTeXResult[]> {
  // Process in parallel with some concurrency limit
  const results: BibTeXResult[] = [];
  const batchSize = 5;

  for (let i = 0; i < queries.length; i += batchSize) {
    const batch = queries.slice(i, i + batchSize);
    const batchResults = await Promise.all(batch.map(q => getBibTeX(q)));
    results.push(...batchResults);
  }

  return results;
}

/**
 * Format multiple BibTeX entries into a single file
 */
export function formatBibTeXFile(entries: BibTeXResult[]): string {
  const validEntries = entries.filter(e => e.bibtex.length > 0);

  if (validEntries.length === 0) {
    return '% No valid BibTeX entries found\n';
  }

  const header = `% Bibliography generated by Bibliography-MCP
% Generated at: ${new Date().toISOString()}
% Total entries: ${validEntries.length}

`;

  return header + validEntries.map(e => e.bibtex).join('\n\n');
}
